openapi: 3.0.2
info:
  version: 0.0.1
  title: Mailtumble.app
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: ''
  description: >
    This is the documentation for the MailTumble public API. 

    # Introduction

    This API definition is intended to to be a good starting point for
    describing your API in 

    [OpenAPI/Swagger
    format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md).

    It also demonstrates features of
    [create-openapi-repo](https://github.com/Redocly/create-openapi-repo) tool
    and 

    [Redoc](https://github.com/Redocly/Redoc) documentation engine. So beyond
    the standard OpenAPI syntax we use a few 

    [vendor
    extensions](https://github.com/Redocly/Redoc/blob/master/docs/redoc-vendor-extensions.md).
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: List
    description: Operations related to lists of emails
  - name: Alias
    description: Operations related to emails within lists
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://staging.example.com/api/v1'
paths:
#  '/users/{username}':
#    $ref: 'paths/users@{username}.yaml'
  /list:
    $ref: paths/list.yaml
  /email:
    $ref: paths/email.yaml
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
